#+INFOJS_OPT: view:overview toc:t
#+OPTIONS: toc:nil
* CL Machine-Learning

CL Machine-Learning is high performance and large scale statistical
machine learning package written in Common Lisp developed at 
[[http://cl-www.msi.co.jp][MSI]].

This repository contains is a authorized fork of the original CLML with the following goals in mind:
  + Remove dependent libraries available from the Quicklisp repository
  + Re-factor code to support Quicklisp packaging 
  + Organize code into independent systems based on functional category
  + Support for SBCL, CCL, LispWorks and Allegro Common Lisp
  + Improve documentation

** Author(s):   
*** Original 
  + Salvi Péter 
  + Naganuma Shigeta
  + Tada Masashi
  + Abe Yusuke
  + Jianshi Huang
  + Fujii Ryo
  + Abe Seika
  + Kuroda Hisao
*** Current Branch Maintainer(s)/Authors(s):    
  +  Mike Maul
*** Contributors:
  +  Graham Dobbins

** [#B] Installation
#+INCLUDE: "./docs/INSTALL.org" :minlevel 2

** Documentation
*** User and API Documentation
+ User and API documentation may be found on line at http://mmaul.github.io/clml/
and also in the project directories docs/clml-manual.html.
+ Tutorials may be found on the clml.tutorials blog at https://mmaul.github.io/clml.tutorials/ 
+ Usage examples can be found in the docs/sample project directory
+ Some notes and algorithmic details and background information can be
found in the project directory docs/notes files in memo, notes and docs

    #+INCLUDE: "./docs/USING.org" :minlevel 2

** Related Repositories
 + clml.extras - https://github.com/mmaul/clml.extras Extended features for clml
   - cl-plplot integration
   - cl-ana integration
   - r-datasets - Library for seamless access to R datasets
   - eazy-gnuplot integration
 + clml.tutorials - https://github.com/mmaul/clml.tutorials Tutorials for CLML

** Contributing
All contributions are welcome. If the contribution is to resolve and
problem with CLML, please open an issue in the github repository 
accompanied by a pull request. 

If you would like to contribute new functionality, again open an issue
at the clml github repository, describe the proposed functionality and
we will go from there. There is a separate repository clml.extras
(https://github.com/mmaul/clml.extras) which is used for functionality
that is not core to CLML but adds features and capabilities, such as
integration layers with other libraries. If this describes your
contribution please open an issue on clml.extras github repository.

If you are interesting in helping to maintain CLML, please contact me
via email. 
